
module.exports = {
  rules: {
    'arrow-body-style': [ 2, 'always' ],
    'arrow-parens': [ 2, 'as-needed', { 'requireForBlockBody': true, } ],
    'arrow-spacing': 2,
    'constructor-super': 2,
    'generator-star-spacing': 2,
    'no-class-assign': 2,
    'no-confusing-arrow': 2,
    'no-const-assign': 2,
    'no-dupe-class-members': 2,
    'no-duplicate-imports': 2,
    'no-new-symbol': 2,
    'no-restricted-imports': 0,
    'no-this-before-super': 2,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': 0,
    'no-var': 2,
    'object-shorthand': 2,
    'prefer-arrow-callback': 0,
    'prefer-const': 2,
    'prefer-numeric-literals': 0,
    'prefer-rest-params': 2,
    'prefer-spread': 1,
    'prefer-template': 2,
    'require-yield': 1,
    'rest-spread-spacing': 2,
    'sort-imports': 0,
    'symbol-description': 2,
    'template-curly-spacing': [ 2, 'never' ],
    'yield-star-spacing': 2,
  },
};
