
module.exports = {
  extends: [
    './rules/best-practices',
    './rules/es6',
    './rules/node',
    './rules/possible-errors',
    './rules/promises',
    './rules/strict-mode',
    './rules/stylistic',
    './rules/variables',
  ].map(require.resolve),
  globals: {
    Buffer: false,
    Promise: true,
    __dirname: false,
    __filename: false,
    clearImmediate: false,
    clearInterval: false,
    console: false,
    exports: false,
    global: false,
    module: false,
    process: false,
    require: false,
    setImmediate: false,
    setInterval: false,
    setTimeout: false,
    document: false,
    window: false,
  },
  parserOptions: {
    ecmaVersion: 2016,
  },
};
